blank_issues_enabled: false
contact_links:
  - name: Simeis Documentation
    url: https://github.com/mxncp85/simeis-ci-cd/tree/main/doc
    about: Merci de consulter la documentation avant de soumettre une issue. Vous y trouverez des guides d'utilisation, des FAQ et des informations sur les fonctionnalités de Simeis.
